version: '3.8'
services:
  backend:
    build: ./backend
    container_name: tere-backend
    ports:
      - "8000:8000"     # No es necesario tunel, pero lo dejo expuesto local por si depuras
    volumes:
      - db_data:/app/data
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: tere-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
